apiVersion: apps/v1
kind: Deployment
metadata:
  name: thursdaydeployement
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: thursdaydeployement
  template:
    metadata:
      name: thursdaydeployement
      labels:
        app: thursdaydeployement
    spec:
      containers:
        - name: mavenuiappcontainer
          image: prashanthmadishetti326/thursdaydeployement
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: thursdaydeployement
  labels:
    app: thursdaydeployement
spec:
  selector:
    app: thursdaydeployement
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
